### ISSUE TITLE
GH Pages

### ISSUE THREAD

**Issue by santiago26** [jbinary/xmpp-blogging-presentation#2]
Feature request: Make this slides accessible via Github Pages.
What to do:
- Accept PR #1. GH Pages requires index.html in root dir. In fact, you can just move the content of output dir to repo root if it's OK for you, instead of accepting PR. 
- Create branch gh-pages
- Visit repo Settings and choose "Default branch" as gh-pages (currently master)
- Delete branch master
- Insert http://jbinary.github.io/xmpp-blogging-presentation into website field in the repo desc 

PROFIT! The presentation will be available at the link above.

**Comment by jbinary** [comment]
Done, thanks.
